### ISSUE TITLE
Files generated with MsBuild task are not part of compilation

### ISSUE THREAD

**Issue by djanosik** [Dresel/Automaty#5]
I suppose it's because the MsBuild target runs before `CoreCompile` but it should probably run before `BeforeBuild`.

**Comment by Dresel** [comment]
It's because

`The "default items" as the .NET SDK calls it are part of the static evaluation of the project file - before any target is run.`

They workaround mentioned [here](https://stackoverflow.com/a/44829863/1249506) should fix this issue, I have also updated a test case to make sure of this.

Please let me know if it works for you when you have time to test it.
